version: '3.8'

services:
  nestjs:
    container_name: 'nestjs_ticketpe'
    build:
      context: .
      target: development
    volumes:
      - .:/usr/src/app
    ports:
      - ${APP_PORT}:${APP_PORT}
      - 9229:9229
    command: npm run start:debug
    env_file:
      - .env
    depends_on:
      - mongodb
  mongodb:
    image: mongo:latest
    container_name: 'mongodb_ticketpe'
    volumes:
      - mongodb_data_container:/data/db
    env_file:
      - .env
    environment:
#      - MONGO_INITDB_DATABASE=${MONGO_DATABASE}
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    ports:
      - ${MONGO_PORT}:${MONGO_PORT}
networks:
  webnet:
volumes:
  mongodb_data_container: